# Generated by Django 5.0.6 on 2024-06-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('Number', models.IntegerField(db_column='number', null=True)),
                ('Number_of_p_p', models.TextField(db_column='number of p/p', null=True)),
                ('Service', models.TextField(db_column='service', null=True)),
                ('Name_of_the_unit', models.TextField(db_column='name of the unit to be serviced', null=True)),
                ('Time', models.TextField(db_column='time')),
                ('January', models.TextField(db_column='january', null=True)),
                ('February', models.TextField(db_column='february', null=True)),
                ('March', models.TextField(db_column='march', null=True)),
                ('April', models.TextField(db_column='april', null=True)),
                ('May', models.TextField(db_column='may', null=True)),
                ('June', models.TextField(db_column='june', null=True)),
                ('July', models.TextField(db_column='july', null=True)),
                ('August', models.TextField(db_column='august', null=True)),
                ('September', models.TextField(db_column='september', null=True)),
                ('October', models.TextField(db_column='october', null=True)),
                ('November', models.TextField(db_column='november', null=True)),
                ('December', models.TextField(db_column='december', null=True)),
                ('Work_performed', models.TextField(db_column='place', null=True)),
                ('Object', models.TextField(db_column='object')),
                ('Place_of_object', models.TextField(db_column='place of object')),
                ('Name', models.TextField(db_column='name')),
            ],
            options={
                'db_table': 'main_timetable',
                'managed': False,
            },
        ),
    ]
